### ISSUE TITLE
no flask module 

### ISSUE THREAD

**Issue by sambhavnoobcoder** [prnvbaraiya/Air-Writing-and-Character-Recognition#1]
requirements.txt does not have flask installation .kindly look into it , I would like to solve the same .

**Comment by bhavaysavaliya** [comment]
@sambhavnoobcoder If you are trying to install libraries and Flask is not being installed, then I think you should change "flask" to "Flask" in the requirements.txt file. This may solve your problem.

**Comment by sambhavnoobcoder** [comment]
okay ,I'll raise a pr with regards to the same.

**Comment by prnvbaraiya** [comment]
Hey @sambhavnoobcoder, Flask is already present in requirement.txt please have a look here is the link to the file - [requirement.txt](https://github.com/prnvbaraiya/Air-Writing-and-Character-Recognition/blob/main/requirement.txt) Line 8. If you are still getting any error please share a screenshot or the description of the error.
